name: Java CI for Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Generate config.properties
        run: bash generate_config.sh
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}


      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install Maven dependencies
      - name: Install Maven dependencies
        run: mvn install -DskipTests=true

      # Step 5: Run Tests (Non-Headless Mode)
      - name: Run Tests
        run: mvn test

      # Step 6: Upload Test Results (Optional)
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/
