name: Java CI for Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

#      - name: Make generate_config.sh executable
#        run: chmod +x generate_config.sh

#      - name: Generate config.properties
#        run: bash generate_config.sh
#        env:
#          USER_NAME: ${{ secrets.USER_NAME }}
#          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Maven dependencies
        run: mvn install -DskipTests=true

      - name: Run Tests with Debug Logs
        run: mvn test -X

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/
